tasks:
  - init: bin/setup
    command: bin/rails server
vscode:
  extensions:
    - copilot-arena.copilot-arenaod.io/docs/introduction/learn-gitpod/gitpod-yaml)
    - aliariff.vscode-erb-beautify
    - Vense.rails-snippets
    - vortizhe.simple-ruby-erbtasks
