# .rubocop.yml
plugins:
  - rubocop-rails
  - rubocop-erb

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  DisplayCopNames: true

  # Include ERB files
  Include:
    - '**/*.rb'
    - '**/*.erb'

  # Common excludes
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 240

Layout/IndentationWidth:
  Width: 2

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 100
