services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    env_file: 
      - .env
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle

volumes:
  bundle_data:
