version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - RAILS_MASTER_KEY=89d8c17fc9a7d3a13db725732cd45f60
    volumes:
      - ".:/rails"
    command: ["./bin/thrust", "./bin/rails", "server"]
